
import type { ChemicalEffect } from '@/components/beaker-icon';

export interface Chemical {
  formula: string;
  name: string;
  isElement?: boolean;
  effects?: Partial<ChemicalEffect>;
}

export const CHEMICAL_CATEGORIES: Record<string, Chemical[]> = {
    ELEMENTS: [
        { formula: 'H', name: 'Hydrogen', isElement: true, effects: { color: '#f0f8ff', glow: 0.1 } }, { formula: 'He', name: 'Helium', isElement: true, effects: { color: '#d3d3d3', bubbles: 1 } },
        { formula: 'Li', name: 'Lithium', isElement: true, effects: { color: '#e0e0e0', explosion: 2 } }, { formula: 'Be', name: 'Beryllium', isElement: true, effects: { color: '#c0c0c0' } },
        { formula: 'B', name: 'Boron', isElement: true, effects: { color: '#a0a0a0' } }, { formula: 'C', name: 'Carbon', isElement: true, effects: { color: '#36454f' } },
        { formula: 'N', name: 'Nitrogen', isElement: true, effects: { color: '#add8e6', bubbles: 1 } }, { formula: 'O', name: 'Oxygen', isElement: true, effects: { color: '#87ceeb', bubbles: 1 } },
        { formula: 'F', name: 'Fluorine', isElement: true, effects: { color: '#98fb98', explosion: 0.1 } }, { formula: 'Ne', name: 'Neon', isElement: true, effects: { color: '#ffc0cb', glow: 0.5 } },
        { formula: 'Na', name: 'Sodium', isElement: true, effects: { color: '#fafad2', explosion: 5 } }, { formula: 'Mg', name: 'Magnesium', isElement: true, effects: { color: '#dcdcdc' } },
        { formula: 'Al', name: 'Aluminum', isElement: true, effects: { color: '#d3d3d3' } }, { formula: 'Si', name: 'Silicon', isElement: true, effects: { color: '#808080' } },
        { formula: 'P', name: 'Phosphorus', isElement: true, effects: { color: '#ffc0cb', glow: 0.2, explosion: 1.5 } }, { formula: 'S', name: 'Sulfur', isElement: true, effects: { color: '#ffff00', smoke: 0.2 } },
        { formula: 'Cl', name: 'Chlorine', isElement: true, effects: { color: '#90ee90', explosion: 0.1 } }, { formula: 'Ar', name: 'Argon', isElement: true, effects: { color: '#dda0dd', glow: 0.4 } },
        { formula: 'K', name: 'Potassium', isElement: true, effects: { color: '#f0e68c', explosion: 6 } }, { formula: 'Ca', name: 'Calcium', isElement: true, effects: { color: '#f5f5dc' } },
        { formula: 'Sc', name: 'Scandium', isElement: true, effects: { color: '#c0c0c0' } }, { formula: 'Ti', name: 'Titanium', isElement: true, effects: { color: '#b0c4de' } },
        { formula: 'V', name: 'Vanadium', isElement: true, effects: { color: '#6a5acd' } }, { formula: 'Cr', name: 'Chromium', isElement: true, effects: { color: '#e6e6fa' } },
        { formula: 'Mn', name: 'Manganese', isElement: true, effects: { color: '#ffdab9' } }, { formula: 'Fe', name: 'Iron', isElement: true, effects: { color: '#a0522d', smoke: 0.1 } },
        { formula: 'Co', name: 'Cobalt', isElement: true, effects: { color: '#4682b4' } }, { formula: 'Ni', name: 'Nickel', isElement: true, effects: { color: '#b0e0e6' } },
        { formula: 'Cu', name: 'Copper', isElement: true, effects: { color: '#b87333' } }, { formula: 'Zn', name: 'Zinc', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'Ga', name: 'Gallium', isElement: true, effects: { color: '#c0c0c0' } }, { formula: 'Ge', name: 'Germanium', isElement: true, effects: { color: '#a9a9a9' } },
        { formula: 'As', name: 'Arsenic', isElement: true, effects: { color: '#808080' } }, { formula: 'Se', name: 'Selenium', isElement: true, effects: { color: '#ffc0cb' } },
        { formula: 'Br', name: 'Bromine', isElement: true, effects: { color: '#a52a2a' } }, { formula: 'Kr', name: 'Krypton', isElement: true, effects: { color: '#afeeee', glow: 0.6 } },
        { formula: 'Rb', name: 'Rubidium', isElement: true, effects: { color: '#f0e68c', explosion: 7 } }, { formula: 'Sr', name: 'Strontium', isElement: true, effects: { color: '#ff6347', glow: 0.3 } },
        { formula: 'Y', name: 'Yttrium', isElement: true, effects: { color: '#d3d3d3' } }, { formula: 'Zr', name: 'Zirconium', isElement: true, effects: { color: '#c0c0c0' } },
        { formula: 'Nb', name: 'Niobium', isElement: true, effects: { color: '#d3d3d3' } }, { formula: 'Mo', name: 'Molybdenum', isElement: true, effects: { color: '#b0c4de' } },
        { formula: 'Tc', name: 'Technetium', isElement: true, effects: { color: '#c0c0c0', glow: 1.2 } }, { formula: 'Ru', name: 'Ruthenium', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'Rh', name: 'Rhodium', isElement: true, effects: { color: '#e6e6fa' } }, { formula: 'Pd', name: 'Palladium', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'Ag', name: 'Silver', isElement: true, effects: { color: '#c0c0c0', sparkles: 2 } }, { formula: 'Cd', name: 'Cadmium', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'In', name: 'Indium', isElement: true, effects: { color: '#c0c0c0' } }, { formula: 'Sn', name: 'Tin', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'Sb', name: 'Antimony', isElement: true, effects: { color: '#a9a9a9' } }, { formula: 'Te', name: 'Tellurium', isElement: true, effects: { color: '#808080' } },
        { formula: 'I', name: 'Iodine', isElement: true, effects: { color: '#4b0082' } }, { formula: 'Xe', name: 'Xenon', isElement: true, effects: { color: '#87ceeb', glow: 0.8 } },
        { formula: 'Cs', name: 'Caesium', isElement: true, effects: { color: '#f0e68c', explosion: 8 } }, { formula: 'Ba', name: 'Barium', isElement: true, effects: { color: '#f5f5dc' } },
        { formula: 'La', name: 'Lanthanum', isElement: true, effects: { color: '#d3d3d3' } },
        { formula: 'Hf', name: 'Hafnium', isElement: true, effects: { color: '#c0c0c0' } }, { formula: 'Ta', name: 'Tantalum', isElement: true, effects: { color: '#b0c4de' } },
        { formula: 'W', name: 'Tungsten', isElement: true, effects: { color: '#808080' } },
        { formula: 'Re', name: 'Rhenium', isElement: true, effects: { color: '#c0c0c0' } }, { formula: 'Os', name: 'Osmium', isElement: true, effects: { color: '#b0c4de' } },
        { formula: 'Ir', name: 'Iridium', isElement: true, effects: { color: '#e6e6fa' } }, { formula: 'Pt', name: 'Platinum', isElement: true, effects: { color: '#d3d3d3', sparkles: 1 } },
        { formula: 'Au', name: 'Gold', isElement: true, effects: { color: '#ffd700', sparkles: 5 } }, { formula: 'Hg', name: 'Mercury', isElement: true, effects: { color: '#e0e0e0', smoke: 0.3 } },
        { formula: 'Tl', name: 'Thallium', isElement: true, effects: { color: '#696969' } }, { formula: 'Pb', name: 'Lead', isElement: true, effects: { color: '#696969' } },
        { formula: 'Bi', name: 'Bismuth', isElement: true, effects: { color: '#ffc0cb', sparkles: 1 } }, { formula: 'Po', name: 'Polonium', isElement: true, effects: { color: '#add8e6', glow: 1.8 } },
        { formula: 'At', name: 'Astatine', isElement: true, effects: { color: '#4b0082', glow: 1.4 } }, { formula: 'Rn', name: 'Radon', isElement: true, effects: { color: '#e0ffff', glow: 1 } },
        { formula: 'Fr', name: 'Francium', isElement: true, effects: { color: '#f0e68c', explosion: 9 } }, { formula: 'Ra', name: 'Radium', isElement: true, effects: { color: '#f5f5dc', glow: 1.5 } },
        { formula: 'Ac', name: 'Actinium', isElement: true, effects: { color: '#c0c0c0', glow: 1.6 } }, { formula: 'Th', name: 'Thorium', isElement: true, effects: { color: '#a9a9a9', glow: 0.6 } },
        { formula: 'Pa', name: 'Protactinium', isElement: true, effects: { color: '#d3d3d3', glow: 1.1 } }, { formula: 'U', name: 'Uranium', isElement: true, effects: { color: '#90ee90', glow: 0.7 } },
        { formula: 'Np', name: 'Neptunium', isElement: true, effects: { color: '#4682b4', glow: 1.3 } }, { formula: 'Pu', name: 'Plutonium', isElement: true, effects: { color: '#ff69b4', glow: 0.9, explosion: 4 } },
    ],
    LIQUIDS: [
        { formula: 'H2O', name: 'Water', effects: { color: '#add8e6' } },
        { formula: 'C2H5OH', name: 'Ethanol', effects: { color: '#f0f8ff' } },
        { formula: 'CH3OH', name: 'Methanol', effects: { color: '#f8f8ff' } },
        { formula: 'CH3COCH3', name: 'Acetone', effects: { color: '#f0ffff' } },
        { formula: 'C3H8O3', name: 'Glycerin', effects: { color: '#fafafa' } },
        { formula: 'C6H14', name: 'Hexane', effects: { color: '#f5f5f5' } },
        { formula: 'C7H8', name: 'Toluene', effects: { color: '#f5f5f5' } },
        { formula: 'CCl4', name: 'Carbon Tetrachloride', effects: { color: '#f8f8f8' } },
        { formula: 'CS2', name: 'Carbon Disulfide', effects: { color: '#f5f5dc' } },
        { formula: 'C6H5Cl', name: 'Chlorobenzene', effects: { color: '#faf0e6' } },
        { formula: 'C4H8O2', name: 'Ethyl Acetate', effects: { color: '#f0fff0' } },
        { formula: 'C5H12', name: 'Pentane', effects: { color: '#f0f8ff' } },
        { formula: 'H2O2', name: 'Hydrogen Peroxide', effects: { color: '#e0ffff', bubbles: 1 } },
    ],
    ACIDS: [
        { formula: 'HCl', name: 'Hydrochloric Acid', effects: { color: '#b0e0e6', smoke: 0.1 } }, { formula: 'H2SO4', name: 'Sulfuric Acid', effects: { color: '#f0f8ff', smoke: 0.4 } },
        { formula: 'HNO3', name: 'Nitric Acid', effects: { color: '#fafad2', smoke: 0.3 } }, { formula: 'CH3COOH', name: 'Acetic Acid', effects: { color: '#f5f5f5' } },
        { formula: 'H3PO4', name: 'Phosphoric Acid', effects: { color: '#f0fff0' } }, { formula: 'H2CO3', name: 'Carbonic Acid', effects: { color: '#f0ffff', bubbles: 2 } },
        { formula: 'HF', name: 'Hydrofluoric Acid', effects: { color: '#e0ffff', smoke: 0.6 } }, { formula: 'HBr', name: 'Hydrobromic Acid', effects: { color: '#e6e6fa', smoke: 0.2 } },
        { formula: 'HI', name: 'Hydroiodic Acid', effects: { color: '#fff0f5', smoke: 0.2 } }, { formula: 'HClO4', name: 'Perchloric Acid', effects: { color: '#f8f8ff', explosion: 0.2 } },
        { formula: 'HClO3', name: 'Chloric Acid', effects: { color: '#f5fffa', explosion: 0.1 } }, { formula: 'HCN', name: 'Hydrogen Cyanide', effects: { color: '#e0ffff', smoke: 0.2 } },
        { formula: 'H2S', name: 'Hydrosulfuric Acid', effects: { color: '#f5f5f5', smoke: 0.5 } }, { formula: 'H3BO3', name: 'Boric Acid', effects: { color: '#fafafa' } },
        { formula: 'H2CrO4', name: 'Chromic Acid', effects: { color: '#fffacd', smoke: 0.2 } },
    ],
    BASES: [
        { formula: 'NaOH', name: 'Sodium Hydroxide', effects: { color: '#f8f8ff' } }, { formula: 'KOH', name: 'Potassium Hydroxide', effects: { color: '#faf0e6' } },
        { formula: 'Ca(OH)2', name: 'Calcium Hydroxide', effects: { color: '#fdf5e6' } }, { formula: 'NH3', name: 'Ammonia', effects: { color: '#f0fff0', smoke: 0.1 } },
        { formula: 'Mg(OH)2', name: 'Magnesium Hydroxide', effects: { color: '#fffafa' } }, { formula: 'LiOH', name: 'Lithium Hydroxide', effects: { color: '#f5fffa' } },
        { formula: 'Ba(OH)2', name: 'Barium Hydroxide', effects: { color: '#fff5ee' } }, { formula: 'Sr(OH)2', name: 'Strontium Hydroxide', effects: { color: '#ffefd5' } },
        { formula: 'NH4OH', name: 'Ammonium Hydroxide', effects: { color: '#f0f8ff' } }, { formula: 'Al(OH)3', name: 'Aluminum Hydroxide', effects: { color: '#f0fff0' } },
        { formula: 'Fe(OH)2', name: 'Iron(II) Hydroxide', effects: { color: '#f5f5f5' } }, { formula: 'Fe(OH)3', name: 'Iron(III) Hydroxide', effects: { color: '#e0cdac' } },
        { formula: 'Zn(OH)2', name: 'Zinc Hydroxide', effects: { color: '#f0f8ff' } }, { formula: 'Cu(OH)2', name: 'Copper(II) Hydroxide', effects: { color: '#e0ffff' } },
        { formula: 'RbOH', name: 'Rubidium Hydroxide', effects: { color: '#f5f5f5' } }, { formula: 'CsOH', name: 'Caesium Hydroxide', effects: { color: '#f5f5f5' } },
    ],
    SALTS: [
        { formula: 'NaCl', name: 'Sodium Chloride', effects: { color: '#ffffff' } }, { formula: 'CuSO4', name: 'Copper Sulfate', effects: { color: '#87ceeb' } },
        { formula: 'KNO3', name: 'Potassium Nitrate', effects: { color: '#f8f8ff' } }, { formula: 'NaHCO3', name: 'Sodium Bicarbonate', effects: { color: '#f5f5f5', bubbles: 4 } },
        { formula: 'AgNO3', name: 'Silver Nitrate', effects: { color: '#e6e6fa' } }, { formula: 'KCl', name: 'Potassium Chloride', effects: { color: '#fffafa' } },
        { formula: 'CaCO3', name: 'Calcium Carbonate', effects: { color: '#fafafa' } }, { formula: 'FeCl3', name: 'Iron(III) Chloride', effects: { color: '#f5deb3' } },
        { formula: 'KI', name: 'Potassium Iodide', effects: { color: '#fafad2' } }, { formula: 'AgCl', name: 'Silver Chloride', effects: { color: '#f8f8ff' } },
        { formula: 'Pb(NO3)2', name: 'Lead(II) Nitrate', effects: { color: '#fffafa' } }, { formula: 'KMnO4', name: 'Potassium Permanganate', effects: { color: '#8a2be2', explosion: 0.1 } },
        { formula: 'CuCl2', name: 'Copper(II) Chloride', effects: { color: '#add8e6' } }, { formula: 'Na2CO3', name: 'Sodium Carbonate', effects: { color: '#f0f0f0' } },
        { formula: 'Na2SO4', name: 'Sodium Sulfate', effects: { color: '#f5f5f5' } }, { formula: 'K2Cr2O7', name: 'Potassium Dichromate', effects: { color: '#ffa500', explosion: 0.2 } },
        { formula: 'NaCN', name: 'Sodium Cyanide', effects: { color: '#f5f5f5' } }, { formula: 'CaSO4', name: 'Calcium Sulfate', effects: { color: '#f0f0f0' } },
        { formula: 'BaSO4', name: 'Barium Sulfate', effects: { color: '#ffffff' } }, { formula: 'MgCO3', name: 'Magnesium Carbonate', effects: { color: '#fafafa' } },
        { formula: 'LiCl', name: 'Lithium Chloride', effects: { color: '#fffafa' } }, { formula: 'SrCl2', name: 'Strontium Chloride', effects: { color: '#fffafa' } },
        { formula: 'BaCl2', name: 'Barium Chloride', effects: { color: '#fffafa' } },
    ],
    GASES: [
        { formula: 'O2', name: 'Oxygen', effects: { bubbles: 3 } }, { formula: 'H2', name: 'Hydrogen', effects: { bubbles: 5, explosion: 0.2 } },
        { formula: 'N2', name: 'Nitrogen', effects: { bubbles: 2 } }, { formula: 'Cl2', name: 'Chlorine', effects: { color: '#90ee90', smoke: 0.5 } },
        { formula: 'CO2', name: 'Carbon Dioxide', effects: { bubbles: 4, smoke: 0.1 } }, { formula: 'SO2', name: 'Sulfur Dioxide', effects: { color: '#f0e68c', smoke: 0.7 } },
        { formula: 'NO2', name: 'Nitrogen Dioxide', effects: { color: '#a0522d', smoke: 0.8 } }, { formula: 'NH3', name: 'Ammonia', effects: { smoke: 0.1 } },
        { formula: 'SO3', name: 'Sulfur Trioxide', effects: { smoke: 0.9 } }, { formula: 'O3', name: 'Ozone', effects: { color: '#87ceeb', bubbles: 2 } },
        { formula: 'C2H4', name: 'Ethene', effects: { bubbles: 2 } }, { formula: 'CH4', name: 'Methane', effects: { bubbles: 3, explosion: 0.1 } },
        { formula: 'NO', name: 'Nitric Oxide', effects: { smoke: 0.3 } },
    ],
    HALOGENS: [
        { formula: 'F2', name: 'Fluorine', effects: { color: '#98fb98', smoke: 0.4, explosion: 0.3 } }, { formula: 'Cl2', name: 'Chlorine', effects: { color: '#90ee90', smoke: 0.5 } },
        { formula: 'Br2', name: 'Bromine', effects: { color: '#a52a2a', smoke: 0.4 } }, { formula: 'I2', name: 'Iodine', effects: { color: '#4b0082', smoke: 0.3 } },
        { formula: 'At2', name: 'Astatine', effects: { color: '#4b0082', smoke: 0.3, glow: 1.5 } },
    ],
    ORGANIC: [
        { formula: 'CH4', name: 'Methane', effects: { bubbles: 3, explosion: 0.1 } }, { formula: 'C6H12O6', name: 'Glucose', effects: { color: '#fafad2' } },
        { formula: 'C3H8', name: 'Propane', effects: { bubbles: 4, explosion: 0.15 } }, { formula: 'C6H6', name: 'Benzene', effects: { color: '#fffacd' } },
        { formula: 'C2H2', name: 'Acetylene', effects: { bubbles: 5, explosion: 0.25 } },
        { formula: 'C7H8', name: 'Toluene', effects: { color: '#fffafa' } }, { formula: 'C8H18', name: 'Octane (Gasoline)', effects: { explosion: 0.2 } },
        { formula: 'C6H5OH', name: 'Phenol', effects: { color: '#f5f5f5' } }, { formula: 'CH2O', name: 'Formaldehyde', effects: { color: '#f0f8ff' } },
        { formula: 'C2H4O2', name: 'Acetic Acid', effects: { color: '#f5f5f5' } }, { formula: 'C12H22O11', name: 'Sucrose', effects: { color: '#fffafa' } },
    ],
    DISPLACEMENT: [
        { formula: 'Zn + CuSO4', name: 'Zinc + Copper Sulfate', effects: { color: '#d3d3d3', bubbles: 2 } },
        { formula: 'Fe + CuSO4', name: 'Iron + Copper Sulfate', effects: { color: '#a0522d', bubbles: 1 } },
        { formula: 'Mg + HCl', name: 'Magnesium + Hydrochloric Acid', effects: { color: '#dcdcdc', bubbles: 8, smoke: 0.1 } },
        { formula: 'Cl2 + KBr', name: 'Chlorine + Potassium Bromide', effects: { color: '#90ee90', bubbles: 1 } },
        { formula: 'Na + H2O', name: 'Sodium + Water', effects: { color: '#fafad2', explosion: 6, smoke: 0.2 } },
    ],
    SPRAYS: [
        { formula: 'Fine Metal Dust', name: 'Fine Metal Dust', effects: { sparkles: 20 } },
        { formula: 'Smoke Powder', name: 'Smoke Powder', effects: { smoke: 1 } },
        { formula: 'Luminol Solution', name: 'Luminol Solution', effects: { glow: 2 } },
        { formula: 'Saturated Carbonate', name: 'Saturated Carbonate', effects: { bubbles: 10 } },
        { formula: 'High-Energy Catalyst', name: 'High-Energy Catalyst', effects: { explosion: 10 } },
        { formula: 'Combustion Promoter', name: 'Combustion Promoter', effects: { color: '#ff4500', glow: 1.5, smoke: 0.5, explosion: 0.1 } },
        { formula: 'Endothermic Agent', name: 'Endothermic Agent', effects: { color: '#e0ffff', glow: 0.5, sparkles: 5 } },
        { formula: 'pH Indicator', name: 'pH Indicator Dye', effects: { color: '#ff00ff' } },
        { formula: 'Graphene Aerogel', name: 'Graphene Aerogel', effects: { bubbles: 8, glow: 0.5, color: '#333333' } },
        { formula: 'Surfactant', name: 'Surfactant', effects: { sparkles: 10, bubbles: 2 } },
        { formula: 'Cryo-Coolant', name: 'Cryo-Coolant', effects: { color: '#a6d9f7', glow: 0.3, sparkles: 3 } },
        { formula: 'Plasma Burst', name: 'Plasma Burst', effects: { color: '#ff00ff', glow: 2, sparkles: 30, explosion: 0.2 } },
        { formula: 'Quantum Foam', name: 'Quantum Foam', effects: { bubbles: 9, glow: 0.8, color: '#e6e6fa' } },
        { formula: 'Bioluminescent Algae', name: 'Bioluminescent Algae', effects: { glow: 1.5, color: '#00ff7f' } },
        { formula: 'Ferrofluid', name: 'Ferrofluid', effects: { color: '#2F4F4F', smoke: 0.2 } },
    ],
};
